name: Earthquake Data Crawler

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  crawl-earthquake-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Run earthquake crawler
        run: npm start
        env:
          NODE_ENV: production
          
      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        if: always() # Upload even if the job fails
        with:
          name: earthquake-data-$(date +%Y%m%d-%H%M%S)
          path: |
            *.json
            *.md
            reports/
          retention-days: 7
          
      - name: Commit and push changes (if any)
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update earthquake data - $(date)"
          git push
